<HTml>
    <head>
        <title>Studi Kasus</title>
    </head>
    <body>
        <form method="get" action="JALAN.PHP">
        <label>Nama Siswa</label>
        <input type="text" name="nama">

        <label>Jenis Kelamin</label>
        <select name="kelamin">
        <option value="L">L</option>
        <option value="p">P</option>
        </select></br>

        <p>
        <label>Asal Sekolah</label>
        <input type="text" name="sekolah">
        <label>No. Telepon</label>

        <input type="text" name="No">
</p>
        <input type="submit" value="Daftar">
</form>
    </body>
</HTml>